[flavor]
use = "matugen"

[manager]
cwd = { fg = "{{colors.primary.default.hex}}" }

# Border and Styles
border_symbol = "│"
border_style  = { fg = "{{colors.outline.default.hex}}" }

# Highlighting for selection
hovered       = { bg = "{{colors.primary_container.default.hex}}", fg = "{{colors.on_primary_container.default.hex}}" }
selection     = { bg = "{{colors.secondary_container.default.hex}}", fg = "{{colors.on_secondary_container.default.hex}}" }

# Status Bar
[status]
separator_open  = ""
separator_close = ""
main            = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }
